version: '3.8'
services:
  redis:
    image: redis
  web_app:
    build: shortener/
    environment:
      PROTO: "https"
      BASE: "s.exp101t.me"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    ports:
      - 127.0.0.1:10001:8000
